9
qwerty-yhn/java-filmorate pull request #1
Opened 2022-12-07 05:17 UTC by qwerty-yhn

2022-12-08 08:27 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом код хороший, давай сделаем его лучше:

1) Исправить то что в коде указал
2) Можно почитать про spring-boot-starter-validation и если будет желание можно применить
3) Почитать про аннотацию @NotBlank, @NotNull, @Email
4) Сильно надо поработать над избежанием дублирования кода

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on HELP.md
> +# Read Me First
Этот файл надо в gitignore добавить

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on mvnw
> +#!/bin/sh
Этот файл надо в gitignore добавить

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Этот файл надо в gitignore добавить

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.6/apache-maven-3.8.6-bin.zip
Этот и файл рядом в папке обычно в github не добавляют, но не критично

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Модификаторы доступа

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Модификаторы доступа

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Убрать дублирование кода

2022-12-08 08:27 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Убрать дублирование кода

2022-12-08 15:52 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
не понял на счет дублирования кода, я убрал строчку import ru.yandex.practicum.filmorate.model.User;  правильно?

2022-12-08 16:42 UTC, qwerty-yhn commented
Сергей добрый день, не знаю увидите или нет. Не много не привычно в новом интерфейсе. Наверное привыкну. На счет аннотаций @notblank, https://github.com/NotNull, @Email интересное решение. В следующем спринте применю обязательно, сократит значительно код. С дублированием тоже вроде поправил, исправил только как я понял)

2022-12-09 17:29 UTC, krylov-sergey-sergeevich commented
Привет, да я вижу все сообщения тут, так как репозиторий публичный

2022-12-09 17:38 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, НО файлы которые в гитигноре добавлены были все еще в pr и будут влиты если влить pr. Поэтому давай я ставлю зачет за задачу, но по пути к 10 дз мы эти файлы из проекта удалим тк они не нужны(особенно в github).

2022-12-09 17:38 UTC, krylov-sergey-sergeevich commented on .gitignore.bak
> +*.class
Странный файл, для чего он если есть уже гитинор

2022-12-09 17:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private int incId(){
Стиль код поехал

2022-12-09 17:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void assertFilm(Film film){
пустая строка перед методом

2022-12-09 17:38 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void assertUser(User user){
Стиль поехал

2022-12-09 17:39 UTC, krylov-sergey-sergeevich commented
Так же по пути к 10 дз жду мелкие правки которые тут отписал.

2022-12-09 17:39 UTC, krylov-sergey-sergeevich commented
Еще название для pull request лучше давать осмысленные

2022-12-22 12:26 UTC, merged