Develop
qwerty-yhn/java-filmorate pull request #17
Opened 2023-01-28 18:41 UTC by qwerty-yhn

2023-01-30 08:31 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа, отметил что можно улучшить, но в целом с небольшими правками будет зачет =)

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    private DirectorController(DirectorService directorService) {
Давайте воспользуемся аннотацией ломбока чтобы без конструктора писать классы

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  public class ErrorHandler {
**Можно лучше:** попробуйте поизучать как в текст ошибки еще добавить путь по которому был запрос это можно сделать при помощи **HttpServletRequest**

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +@RestController("FeedController")
А зачем в скобках ("FeedController") ?

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +        userService.getUserId(id);
А зачем тут этот вызов?

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    public List<Event> findById(@PathVariable int id) {
Исправить название на getById

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        throw new DirectorNotFoundException("Режиссер с id" + directorId + " не найден");
Давай доработаем исключение так чтобы new DirectorNotFoundException(directorId); вот так писать а текст исключения остался в итоге таким же это делается при помощи доработки конструктора в исключение

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +@Service("FeedService")
("FeedService") - зачем?

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        throw new DirectorNotFoundException("Режиссер с id" + directorId + " не найден");
**Можно лучше:** new DirectorNotFoundException(directorId); - можно переработать исключение так чтобы самому не писать текст ошибки каждый раз

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDBStorage.java
> +    public DirectorDBStorage(JdbcTemplate jdbcTemplate) {
Давайте воспользуемся аннотацией ломбока чтобы без конструктора писать классы

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            List<Integer> l = jdbcTemplate.query("SELECT DISTINCT FILM_ID  FROM LIKE_FILM WHERE USER_ID = ?", this::mappingInteger, inc);
название переменной совсем непонятное

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        HashMap<Integer, List<Integer>> hashMapWithLikingList = new HashMap<>();
Зачем нам в определение типа знать что это именно HashMap?
Можно сделать так
Map<Integer, List<Integer>> hashMapWithLikingList

второй момент в название переменной писать тип полностью это некорректно ИНОГДА крайне редко можно добавить или List или Map но не полный тип
поэтому лучше сделать название подобным
что-то MapToLikes например

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return null;
Почему null а не пустой например? 

p.s это вопрос любопытства а не ТЗ

2023-01-30 08:31 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Опасная операция, но в тестовом проекте терпимо

2023-01-30 14:53 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    private DirectorController(DirectorService directorService) {
Поправил)

2023-01-30 16:07 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +        userService.getUserId(id);
Проверка на несуществующих пользователей, что бы не дублировать код сделали так, сейчас я его в метод getUserId внес, такая получилась специфика кода))

2023-01-30 16:48 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        throw new DirectorNotFoundException("Режиссер с id" + directorId + " не найден");
Создал 2 конструктора, один на вход integer другой string

2023-01-30 17:34 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            List<Integer> l = jdbcTemplate.query("SELECT DISTINCT FILM_ID  FROM LIKE_FILM WHERE USER_ID = ?", this::mappingInteger, inc);
А нам на каком то из вебинаров говорили что можно применять односимвольные имена, хотя это наверное к циклам больше относится)

2023-01-30 17:34 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            List<Integer> l = jdbcTemplate.query("SELECT DISTINCT FILM_ID  FROM LIKE_FILM WHERE USER_ID = ?", this::mappingInteger, inc);
Поправил

2023-01-30 17:38 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        HashMap<Integer, List<Integer>> hashMapWithLikingList = new HashMap<>();
Так действительно лучше)

2023-01-30 17:55 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            return null;
Я все равно поправил) вообще другого параметра не должно быть, поэтому наверное лучше exeption выбрасывать throw new DirectorNotFoundException("Не верный тип сортировки");

2023-01-30 18:04 UTC, qwerty-yhn commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Я так думаю это ввели для того чтобы не удалять каждый раз filmorate.db, может быть ошибаюсь, но очень похоже. Я использую так 
spring.datasource.url=jdbc:h2:mem:./db/filmorate
#spring.datasource.url=jdbc:h2:file:./db/filmorate

2023-01-30 18:05 UTC, qwerty-yhn commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Я удалил DROP ALL OBJECTS

2023-01-30 19:11 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  public class ErrorHandler {
Интересная задача, и я не понял а откуда этот класс знает сам URI? я прочитал но не понял как применить. Посмотри в файлике MpaNotFoundException и DirectorController инфу от сюда брал(https://www.baeldung.com/java-httpservletrequest-mock) может направишь

2023-01-30 19:21 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>  public class ErrorHandler {
А можно на счет этой задачи я в пачке тебе напишу? писать обещаю не много

2023-01-31 13:11 UTC, qwerty-yhn commented
Сергей привет!) Правки внес, все перепроверил. Не смог только с классом HttpServletRequest разобраться, но в ответах отписался)

2023-02-01 08:06 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

p.s. на счет проверки существования пользователя рекомендую все же в будущем отдельный метод сделать checkUserExist(id)

2023-02-06 01:56 UTC, merged