Check project, sprint '10' commit '1'
qwerty-yhn/java-filmorate pull request #2
Opened 2022-12-22 12:51 UTC by qwerty-yhn

2022-12-22 12:56 UTC, qwerty-yhn commented
Сергей здравствуйте, из проекта я файл gitignore.back удалил а из gitHib не могу)

2022-12-23 20:51 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохая работа, давай доработаем:
1) Необязательно, но прям желательно: ExceptionHandler изучить и сделать
2) Поправить то что в коде отпишу
3) Можно побаловаться аннотациями из validation и где требуется нужные поставить

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on .gitignore.bak
>  hs_err_pid*
Его надо еще локально удалить

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Почему используем этот логгер а не от ломбока?

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Давай вместо конструктора будем аннотацию из ломбока использовать  @requiredargsconstructor

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> findAll(
почему название метода findAll а не получение популярных

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Аналогичный вопрос к конструктору и логгеру

2022-12-23 20:51 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
Может Int сделаем?

2022-12-23 20:55 UTC, krylov-sergey-sergeevich requested changes
Случайно прошлое ревью отправил, не дописав замечания, вот теперь все =)

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private Long incId(){
Стиль поехал

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void assertFilm(Film film){
Вот эту валидацию можно чутка помочь при помощи аннотаций validation и в контроллер вынести если вдруг

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private Long incId(){
Дублируется, давай исправим и создадим специальный утилитный класс

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ResponseStatusException(
Почему при нашей внутренней бизнес ошибке мы кидаем ошибку из фреймворка спринга?

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private HashMap<Long, User> userHashMap = new HashMap<>();
final

2022-12-23 20:55 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
>      public void testAddFilm(){
Эх, все тесты убрались =(

2022-12-25 04:09 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
по примеру из теории, честно говоря не знал даже о его существовании, прочитаю

2022-12-25 05:04 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
Поправил, только в ТЗ приводится пример что хранить юзеров вы должны в hashmap<Long, User> где ключ это id поэтому я сделал вывод что id должен быть Long. Просто все эти преобразования Long.value на мой взгляд нагромождения кода

2022-12-25 08:41 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new ResponseStatusException(
Не понимаю почему так работает, я создал отдельный класс ErrorHangler там прописал исключение UserNotFoundException, но оно почему то не попадает туда... а прописал в  UserController все работает)

2022-12-25 09:03 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    private Long incId(){
Я попытался это сделать, но тут такая проблема что  id для film и для user они должны считать не зависимо друг от друга, тесты постмана не проходит тогда. Я их назвал как incIdFilm и incIdUser.

2022-12-25 09:13 UTC, qwerty-yhn commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
>      public void testAddFilm(){
))) А я исключительно на ТЗ полагался, там написано что протестируйте с помощью Postmana

2022-12-25 10:43 UTC, krylov-sergey-sergeevich requested changes
Привет, как-то очень выборочно по ощущению правки сделаны, просьба еще раз перечитать все что было написано и учесть в доработках

- Еще важный момент - давай коммиты называть более кхм соответствующе, чтобы спустя пол года по названию было понятно что было сделано =)

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
@ControllerAdvice - надо добавить

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Map<String, String> handleNegativeCount(final UserNotFoundException e) {
Надо доработать так чтобы эта штука была в ErrorHandlers

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(UserController.class);
Лучше уже сейчас перейти это будет кхм правильнее

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
id и должен быть Long, комментарий же к строчке Duration =)

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage inMemoryFilmStorage) {
Может аннотацию ломбока вместо конструктора?

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ResponseStatusException(
Не исправлено

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage inMemoryUserStorage) {
Аннотацию вместо конструктора

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(InMemoryFilmStorage.class);
Ломбок логгер вместо этого

2022-12-25 10:43 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +@Component
Пару пустых строк перед аннотацией - это правила стиля кода

2022-12-25 15:37 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private int duration;
Сергей а можете подробнее написать про int, duration и так int

2022-12-25 16:07 UTC, qwerty-yhn commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ResponseStatusException(
Я  для User сделал, а для Film нет, сейчас поправил

2022-12-25 16:26 UTC, qwerty-yhn commented
Сергей, я не все правки вижу, их много. Я к яндексу привыкал, и понял что к чему, а в гитхабе еще в процессе. Поэтому прошу меня извинить, что приходится по несколько раз перепроверять.

2022-12-26 11:50 UTC, krylov-sergey-sergeevich approved these changes
Привет, ставлю зачет, но давай по пути к 11 дз поправим все заметки.

Ничего страшного привыкнешь к гитхабу, дело привычки = )

2022-12-26 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +@ControllerAdvice
Пару пустых строк перед аннотацией

2022-12-26 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new FilmNotFoundExeption("нет такого фильма");
Вопрос, какого? Давай в текст ошибки еще айди фильма который не нашли писать

2022-12-26 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new FilmNotFoundExeption("нет такого фильма");
И давай текст по английски писать это более правильно в реальной разработке

2022-12-26 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    final private HashMap<Long, User> userHashMap = new HashMap<>();
private final Map<Long, User> userHashMap - так правильнее

2022-12-26 11:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new UserNotFoundException("Нет такого user");
Текст по английски и айди добавить

2023-01-19 14:47 UTC, merged