Add database
qwerty-yhn/java-filmorate pull request #3
Opened 2023-01-17 15:02 UTC by qwerty-yhn

2023-01-18 10:29 UTC, krylov-sergey-sergeevich requested changes
Привет, работа неплохая, но давай чутка перекомпонуем и поправим по замечаниями:
Нужны следующие компоненты (нужно в них вынести что к ним будет относиться):
- FriendDbStorage, LikeDbStorage - свои запросы по добавлению и удалению
- GenreDbStorage, MpaDbStorage - только getById + getAll

Так-же в файле README.md должна быть ссылка на файл диаграммы

На счет исключений рекомендую сразу думать так "А что я подумаю если увижу это исключение" и тогда будет легче делать их более корректными.

Буду ждать с доработкой и если есть вопросы пиши в пачке обсудим или в коментах в коде =)

2023-01-18 10:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public UserDbStorage(JdbcTemplate jdbcTemplate) {
Давай вместо конструктора будем аннотацию из ломбока использовать  @requiredargsconstructor

2023-01-18 10:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            throw new UserNotFoundException("Пользователь не найден");
Вот в логах ты увидишь такое сообщение и как поймешь какой человек именно не найден? Нужно добавить какой то id или что-то что поможет лучше понимать логи

2023-01-18 10:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +            throw new UserNotFoundException("Пользователь не найден");
Аналогично какой человек?

2023-01-18 10:29 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/utility/Util.java
> +public class Util {
Удалим класс?

2023-01-18 10:29 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +
Есть ощущение что стиль чутка поехал.

- рекомендую primary key делать как constraint внизу в определение таблицы, но это не обязательно
- почитай про unique в sql и может придет идея где его применить можно

2023-01-18 14:23 UTC, qwerty-yhn commented on src/main/resources/schema.sql
> +
Для каждого dao добавил сервис и контроллер надеюсь так и надо было, просто это хотя бы логике подчиняется, по поводу таблицы и констрейн у меня ругаться идея начала, что то я делаю не так, еще почитаю сторонню литературу, в нынешнем курсе такого нет. Еще я не понял где применять @Qualifer

2023-01-19 06:47 UTC, krylov-sergey-sergeevich approved these changes
Привет, хорошо переработано, на счет qulifier это редкая штука и используется когда есть 2 бина одного класса и надо выбрать какой использовать, по хорошему такого в приложение нормальном не должно быть.

Прошу к следующему дз подумать и сделать так чтобы вместо подобных исключений:

new FilmNotFoundExeption("Фильм c id = " + id + " не найден");
было
new FilmNotFoundExeption(id);
НО текст ошибки остался такой же в логах и ответе программы, это можно сделать при помощи дополнительного конструктора в классе исключения, прошу подумать и если не выйдет подскажу в следующем дз.

Удачи =)

2023-01-19 14:47 UTC, merged